### ISSUE TITLE
TravisCI build broken due to Meson

### ISSUE THREAD

**Issue by BBasile** [dlang-community/D-YAML#82]
cc @ximion.

**Comment by ximion** [comment]
That's a weird one... It looks like the `before_install` section is not executed by Travis at all... I wonder whether this is actually a bug in Travis...

**Comment by ximion** [comment]
Ah, Travis fooled me and displayed a PR instead of the actual failure in the master branch...
Looks like this is old friend Travis bug https://github.com/travis-ci/travis-ci/issues/8363, where Travis changed its behavior when rolling out another base image regarding Python.
Since we are not actually testing Python versions here, I think adding a workaround is acceptable, so that fixes that.

The other issue unfortunately is that we are also hit by Meson bug https://github.com/mesonbuild/meson/issues/2719 where I am still waiting for feedback.
I could add a workaround to D-YAML for that particular issue though.
